MenuOptions:
  - label: "Nettoyer l'espace disque"
    function: "Clear-DiskSpace"
    SupportsDemo: false
    params: {}

  - label: "Compression Image"
    function: "Compress-Image"
    SupportsDemo: true
    params: {}
