# Config/config_interface.yaml
Interface:
  Title: "TS Toolbox by Massin Lionel"
  Size:
    Width: 800
    Height: 600
  StartPosition: CenterScreen
  DemoPassword: "Temps*13245"
  ListBox:
    Location:
      X: 10
      Y: 10
    Size:
      Width: 300
      Height: 200
  LogTextBox:
    Location:
      X: 10
      Y: 220
    Size:
      Width: 780
      Height: 300
  ProgressBar:
    Location:
      X: 320
      Y: 10
    Size:
      Width: 470
      Height: 30
    Minimum: 0
    Maximum: 100
  Buttons:
    Run:
      Text: "Exécuter"
      Location:
        X: 10
        Y: 530
      Size:
        Width: 100
        Height: 30
    Exit:
      Text: "Quitter"
      Location:
        X: 120
        Y: 530
      Size:
        Width: 100
        Height: 30
