Interface:
  Title: "TS Toolbox"
  Size: { Width: 800, Height: 600 }
  StartPosition: CenterScreen
  ListBox:
    Location: { X: 10, Y: 10 }
    Size: { Width: 300, Height: 200 }
  LogTextBox:
    Location: { X: 10, Y: 220 }
    Size: { Width: 780, Height: 300 }
  ProgressBar:
    Location: { X: 320, Y: 10 }
    Size: { Width: 470, Height: 30 }
    Minimum: 0
    Maximum: 100
  Buttons:
    Run:
      Text: "Exécuter"
      Location: { X: 10, Y: 530 }
      Size: { Width: 100, Height: 30 }

ModeChooser:
  Title: "TS Toolbox - Choix du mode"
  Size: { Width: 300, Height: 120 }
  Buttons:
    Demo:
      Text: "Mode Démo"
      Location: { X: 30, Y: 40 }
      Size: { Width: 100, Height: 30 }
    Prod:
      Text: "Mode Prod"
      Location: { X: 160, Y: 40 }
      Size: { Width: 100, Height: 30 }
