MenuOptions:
  - label: "Nettoyer l'espace disque"
    function: "Clear-DiskSpace"
    SupportsDemo: true
    params: {}

  - label: "Vérifier l'état du disque"
    function: "Check-DiskStatus"
    SupportsDemo: false
    params: {}
