Interface:
  Title: "Boîte à outils PowerShell"
  Size:
    Width: 600
    Height: 600
  StartPosition: "CenterScreen"
  ListBox:
    Location: { X: 10,  Y: 10 }
    Size:     { Width: 260, Height: 480 }
  LogTextBox:
    Location: { X: 280, Y: 10 }
    Size:     { Width: 300, Height: 500 }
  ProgressBar:
    Location: { X: 10,  Y: 500 }
    Size:     { Width: 260, Height: 20 }
    Minimum: 0
    Maximum: 100
  Buttons:
    Run:
      Text: "Exécuter"
      Location: { X: 10,  Y: 530 }
      Size:     { Width: 100, Height: 30 }
    Exit:
      Text: "Quitter"
      Location: { X: 120, Y: 530 }
      Size:     { Width: 100, Height: 30 }
