MenuOptions:
  - label: "Nettoyer l'espace disque"
    function: "Clear-DiskSpace"
    SupportsDemo: false
    params: {}

  - label: "Compression Image"
    function: "Compress-Image"
    SupportsDemo: true
    params:
      inputFolder: "C:\\Photos"
      quality: 80
      dateLimit: "2027-01-01"

  - label: "Symlink"
    function: "Out-Symlink"
    SupportsDemo: false
    params: {}
