MenuOptions:
  - label: "Nettoyer l'espace disque"
    function: "Clear-DiskSpace"
    SupportsDemo: true
    params: []

  - label: "Compression Image"
    function: "Compress-Image"
    SupportsDemo: true
    params:
      - Name: "InputFolder"
        Type: "path"
        Default: "C:\\Photos"
        Prompt: "Dossier source des images"
      - Name: "Quality"
        Type: "percent"
        Default: 80
        Prompt: "Qualité JPEG (1-100)"
      - Name: "DateLimit"
        Type: "datetime"
        Default: "2025-01-01"
        Prompt: "Ne traiter que les fichiers antérieurs à (YYYY-MM-DD)"

  - label: "Symlink Outlook"
    function: "Out-Symlink"
    SupportsDemo: false
    params:
      - Name: "UsersPath"
        Type: "path"
        Default: "C:\\Users"
        Prompt: "Chemin des profils utilisateurs"
      - Name: "ExpectedTargetPattern"
        Type: "string"
        Default: "D:\\USERS\\{user}\\Outlook"
        Prompt: "Modèle de cible attendu pour les liens symboliques"
